### ISSUE TITLE
License for edit-by-index/editing-trace.js

### ISSUE THREAD

**Issue by mohe2015** [automerge/automerge-perf#1]
Hi,

can you clarify how https://github.com/automerge/automerge-perf/blob/master/edit-by-index/editing-trace.js is licensed, please? It would be best if you could add a `LICENSE` file or something similar.

Kind regards
Moritz

**Comment by ept** [comment]
Good idea, thank you! I added a CC-BY license: 05610fe303c0ef291199387786f1a28fa4556643
